---
driver:
  name: docker
platforms:
  - name: instance-ubuntu
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
  - name: instance-oraclelinux
    image: geerlingguy/docker-oraclelinux8-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
