---
- name: Verify
  hosts: all
  tasks:
    - name: Check directory exists
      ansible.builtin.stat:
        path: /opt/vector
      register: dir_check
    - name: Assert directory exists
      ansible.builtin.assert:
        that:
          - dir_check.stat.exists
