name: Molecule tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install molecule==3.5.2 molecule-podman==1.0.2 ansible==6.0.0
      - name: Run molecule test
        run: molecule test
