name: Molecule tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install 'molecule==6.0.0' 'molecule-docker==2.0.0' 'ansible==7.5.0' 'docker==6.0.1'
      - name: Run molecule test
        run: molecule test
